### PR TITLE
Use Pimple idiom for Network Interface Listener

### PR DESCRIPTION
**Pull request by LuxoftAKutsan**
Fixes #[issue number]

This PR is ready for review.

### Risk

This PR makes no API changes. 

### Summary

Create `qnx` and `linux` folder with platform specific code.

Moved implementation from network_interface_listener_impl to
platform_specific/linux/platform_specific_network_interface_listener_impl

QNX contains empty implementation

Renamed source files : used cc file extension for source files

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by AStasiuk** [comment]
Manual Test set: [ManualTestCases_v1.1.pdf](https://github.com/XevoInc/sdl_core/files/2098778/ManualTestCases_v1.1.pdf)
Example adding implementation for custom_os: [Adding_Additional_Implementation_of_Network_Interface_Listener.pdf](https://github.com/XevoInc/sdl_core/files/2098780/Adding_Additional_Implementation_of_Network_Interface_Listener.pdf)
Detailed design document: [NetworkInterface_refactoring_proposal.pdf](https://github.com/XevoInc/sdl_core/files/2098782/NetworkInterface_refactoring_proposal.pdf)

**Comment by AStasiuk** [comment]
@askirk, @mrapitis, @yang1070, @robinmk please review

**Comment by martingkelly** [comment]
Hi, did you mean to make this PR to the XevoInc repository or the upstream https://github.com/smartdevicelink/sdl_core ?

**Comment by shoamano83** [comment]
Hi @askirk, I reached out our admin but unfortunately it wasn't possible to add a reviewer who is outside of the organization.

I can do the merge to XevoInc:feat/mt_transport_changes branch. So please use the comment fields or whatever available for your code review. Once everybody is happy, I will merge it. Does it sound good to you?

Also, please allow me to do them in Thursday morning JST...

**Review by shoamano83 — APPROVED** [review]
Thank you. I went through the changes and they look good to me.
Let me know when everybody's review is completed. Then I will go on merging. Thanks.

**Comment by askirk** [comment]
Approved by me, reviewed and tested with SPT.

**Comment by shoamano83** [comment]
OK I'm merging this now.

**Pull request merged**
